//! StellarTip — Rust example (cross-contract integration)
//!
//! This file shows the canonical pattern for calling the StellarTip contract
//! from **another** Soroban contract.
//!
//! At compile time `soroban_sdk::contractimport!` reads the WASM build
//! artifact of the StellarTip contract and generates a typed Rust client
//! (`stellar_tip::Client`) that you can call as if it were a regular Rust
//! type. The orchestrator contract below wraps `stellar_tip::Client::tip()`
//! so a single host-level call performs the same work as a normal tip —
//! moving tokens from `from` → contract → fee-recipient → creator credit,
//! recording the tip in history, and emitting the `TIP` event.
//!
//! Prereqs (from the parent `examples/README.md`):
//!
//!   # 1. Build the StellarTip WASM first; the contractimport! macro needs
//!   #    the artifact on disk to read its exported method shapes.
//!   cd ../.. && make wasm-build
//!
//!   # 2. From this directory, compile against wasm32-unknown-unknown.
//!   cargo build --release --target wasm32-unknown-unknown
//!
//! SDK target: `soroban-sdk =21.7.7` (matches the parent crate's
//! `Cargo.toml`).

#![no_std]

use soroban_sdk::{contract, contractimpl, contractimport, Address, Env, String, Symbol};

// ---------------------------------------------------------------------------
// Generate a typed `stellar_tip` module from the live StellarTip WASM
// artifact.
//
// - `file` is relative to *this* file. We sit at
//   `examples/rust/src/lib.rs`, so three `..` segments walk us back to the
//   repo root, then into `target/`. Adjust if you copy this snippet into a
//   different project layout.
// - `name = "stellar_tip"` pins the generated module name so the rest of
//   this file can reference `stellar_tip::Client` directly. Without it,
//   the macro names the module after the WASM metadata / struct name and
//   the references below would not resolve.
// ---------------------------------------------------------------------------
contractimport!(
    file = "../../../target/wasm32-unknown-unknown/release/stellar_tip.wasm",
    name = "stellar_tip",
);

// ---------------------------------------------------------------------------
// Orchestrator contract
// ---------------------------------------------------------------------------

/// Tiny on-chain glue contract that forwards a tip call to StellarTip.
///
/// Use case: a creator program on Stellar (e.g. a content-paywall, a
/// subscription service, or a marketplace contract) that wants to settle
/// tips through StellarTip without re-implementing the fee math, auth,
/// or storage code. The orchestrator simply re-exposes `tip()` so the
/// call can be composed with whatever business logic the host contract
/// already needs.
#[contract]
pub struct StellarTipOrchestrator;

#[contractimpl]
impl StellarTipOrchestrator {
    /// Forward a single tip into StellarTip, attributing it to `from`.
    ///
    /// `from.require_auth()` here satisfies the same auth requirement that
    /// `stellar_tip::Client::tip` will check inside the StellarTip contract
    /// — the orchestrator's address then re-authorizes on its own behalf
    /// through the cross-contract call envelope.
    ///
    /// Returns the same `u64` index that `tip()` does: the new tip's
    /// position in the creator's history.
    pub fn submit_tip(
        env: Env,
        from: Address,
        stellar_tip: Address,
        creator: Address,
        token: Address,
        amount: i128,
        message: String,
    ) -> u64 {
        // 1. The supporter authorizes this tip from their wallet.
        from.require_auth();

        // 2. Build the typed client. `Client` was generated by the macro
        //    above around the same shape you see in src/lib.rs:
        //        pub fn tip(
        //            &self,
        //            from: &Address,
        //            creator: &Address,
        //            token: &Address,
        //            amount: &i128,
        //            message: &String,
        //        ) -> u64
        let tip = stellar_tip::Client::new(&env, &stellar_tip);

        // 3. Forward. The StellarTip contract will validate auth a second
        //    time (this time on the orchestrator's address), enforce the
        //    `MinTipAmount` / `MaxTipsPerCreator` / `Paused` checks, move
        //    tokens via the SAC, credit the creator's internal balance,
        //    append the tip to history, and emit the `TIP` event.
        let index = tip.tip(&from, &creator, &token, &amount, &message);

        // 4. Optional: emit a domain-specific event so off-chain indexers
        //    can observe orchestrator-mediated tips independently.
        env.events()
            .publish(("ORCH_TIP", from.clone()), (creator.clone(), index, amount));

        index
    }

    /// Forward a creator registration to StellarTip.
    ///
    /// Same pattern as `submit_tip` but using the `register` client method.
    /// `username` is a `Symbol` on the StellarTip side, capped at 32 bytes
    /// by the underlying `ScSymbol` type — keep names ≤ 32 ASCII chars to
    /// avoid rejection with `InvalidInput` (#12).
    pub fn register_creator(
        env: Env,
        caller: Address,
        stellar_tip: Address,
        username: Symbol,
        display_name: String,
        bio: String,
    ) {
        caller.require_auth();

        let tip = stellar_tip::Client::new(&env, &stellar_tip);
        tip.register(&caller, &username, &display_name, &bio);

        env.events()
            .publish(("ORCH_REG", caller.clone()), username);
    }
}

/*
 * ===== EXPECTED OUTPUT =====================================================
 *
 * This file is an orchestrator contract — it has no console output of its
 * own. Output happens at the *host* level when the orchestrator is invoked
 * from a Soroban transaction. Below is a representative invocation against
 * a deployed orchestrator instance.
 *
 * Caller transaction (via `stellar contract invoke`):
 *
 *   stellar contract invoke \
 *     --id "$ORCHESTRATOR_ID" \
 *     --network testnet \
 *     --source supporter \
 *     -- submit_tip \
 *     --from             "$SUPPORTER_PK" \
 *     --stellar_tip      "$CONTRACT_ID" \
 *     --creator          "$CREATOR_PK" \
 *     --token            "$XLM_TOKEN" \
 *     --amount           10000000 \
 *     --message          "Love your art!"
 *
 * ...returns the new tip index, e.g. `0`.
 *
 * Resulting on-chain events (in topic order):
 *
 *   ORCH_TIP  topic=($SUPPORTER_PK,)  payload=($CREATOR_PK, 0, 10000000)
 *   TIP       topic=($SUPPORTER_PK,)  payload=($CREATOR_PK, $XLM_TOKEN, 10000000, 250000, 0)
 *
 * Read back after the call:
 *
 *   stellar contract invoke --id "$CONTRACT_ID" --network testnet -- \
 *     get_tip_count --creator "$CREATOR_PK"
 *   # → 1
 *
 *   stellar contract invoke --id "$CONTRACT_ID" --network testnet -- \
 *     get_balance  --creator "$CREATOR_PK" --token "$XLM_TOKEN"
 *   # → 9750000   (10_000_000 - 2.5 % platform fee at `fee_bps = 250`)
 *
 * The same fee math applies as in the TypeScript and Python examples:
 *
 *   fee = (amount * fee_bps) / 10_000
 *   creator credit = amount - fee
 *
 * ============================================================================
 */
